---
abstract: 'Crypt::CBC compliant Rijndael encryption module'
author:
  - 'Rafael R. Sevilla (maintained by brian d foy <bdfoy@cpan.org>)'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Rijndael
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/crypt-rijndael
version: 1.12
